package pk.onlinebazaar.helpers;

import pk.onlinebazaar.R;
import android.app.Activity;
import android.app.Dialog;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.Window;
import android.widget.Button;
import android.widget.TextView;

public class TermsAndConditionDialog extends Dialog{

	TextView tvTermsAndCondition;
	Button btnAccept;

	public Activity c;
	public android.view.View.OnClickListener onClickListener;
	
	public TermsAndConditionDialog(Activity a, android.view.View.OnClickListener onClickListener) {
		super(a);
		this.c = a;
		this.onClickListener = onClickListener;
	}

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		requestWindowFeature(Window.FEATURE_NO_TITLE);
		setContentView(R.layout.terms_conditions);

		tvTermsAndCondition = (TextView) findViewById(R.id.wvTermsAndConditions);
		btnAccept = (Button) findViewById(R.id.btnAccept);

		btnAccept.setOnClickListener((android.view.View.OnClickListener) onClickListener);

		SpannableBuilder builder = new SpannableBuilder(c);
		builder.append("Introduction\n\n", Typeface.BOLD)
				.append("This Site is provided by Online Bazaar (referred to throughout this Site as \"OnlineBazaar.pk\") as a service to our customers. Please review the following basic rules that govern your use of the OnlineBazaar.pk site. ")
				.append("Please note that your use of the OnlineBazaar.pk site constitutes your unconditional agreement to follow and be bound by these Terms of Use. ",
						Typeface.BOLD)
				.append("Although you may \"bookmark\" a particular portion of this Site and thereby bypass these Terms of Use, your use of this Site still binds you to these Terms of Use. OnlineBazaar.pk reserves the right to update or modify these Terms of Use at any time without prior notice to you. For this reason, we recommend that you review these Terms of Use whenever you use this Site.")
				.append("\n\n Use of this Site\n\n", Typeface.BOLD)
				.append("If you do not agree to (or cannot comply with) any of these terms and conditions, do not use this Site. All billing and registration information provided must be truthful and accurate. Providing any untruthful or inaccurate information constitutes a breach of these Terms of Use. By confirming your purchase at the end of the checkout process, you agree to accept and pay for the item(s) requested.\n")
				.append("All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips or downloads, video clips and written and other materials that are part of this Site (collectively, the \"Contents\") are intended solely for personal, non-commercial use. You may download or copy the Contents and other downloadable materials displayed on the Site for your personal use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Contents, the Site or any related software. All software used on this Site is the property of OnlineBazaar.pk or its suppliers and protected by Pakistan and international copyright laws. The Contents and software on this Site may be used only as a shopping resource. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance, of the Contents on this Site is strictly prohibited.\n")
				.append("Third Party Sites: References on this Site to any names, marks, products or services of third parties, or hypertext links to third party sites or information are provided solely as a convenience to you and do not in any way constitute or imply OnlineBazaar.pk's endorsement, sponsorship or recommendation of the third party, its information, products or services. OnlineBazaar.pk is not responsible for the practices or policies of such third parties, nor the content of any third party sites, and does not make any representations regarding third party products or services, or the content or accuracy of any material on such third party sites. If you decide to link to any such third party sites, you do so entirely at your own risk.")
				.append("\n\nSite Security\n\n", Typeface.BOLD)
				.append("You are prohibited from violating or attempting to violate the security of the Site, including, without limitation, (a) accessing data not intended for such user or logging onto a server or an account which the user is not authorized to access; (b) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; (c) attempting to interfere with service to any user, host or network, including, without limitation, via means of submitting a virus to the Site, overloading, \"flooding,\" \"spamming,\" \"mailbombing\" or \"crashing;\" (d) sending unsolicited email, including promotions and/or advertising of products or services; or ")
				.append(" (e) forging any TCP/IP packet header or any part of the header information in any email or newsgroup posting. Violations of system or network security may result in civil or criminal liability. OnlineBazaar.pk will investigate occurrences that may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of this Site or any activity being conducted on this Site. You agree, further, not to use or attempt to use any engine, software, tool, agent or other device or mechanism (including without limitation browsers, spiders, robots, avatars or intelligent agents) to navigate or search this Site other than the search engine and search agents available from OnlineBazaar.pk on this Site and other than generally available third party web browsers (e.g., Netscape Navigator or Microsoft Explorer).")
				.append("\n\nOrder Acceptance\n\n", Typeface.BOLD)
				.append("Please note that there may be certain orders that we are unable to accept and must cancel. We reserve the right, at our sole discretion, to refuse or cancel any order for any reason. For your convenience, you will not be charged until your payment method is authorized, the order information is verified for accuracy and your order is shipped (except for orders, including pre-orders, paid for with a Credit Card, Debit Card, Bank Card or PayPal account which are charged at the time you place your order, not when your order is shipped).")
				.append(" Some situations that may result in your order being canceled include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information, or problems identified by our credit and fraud avoidance department. We may also require additional verifications or information before accepting any order. We will contact you if all or any portion of your order is canceled or if additional information is required to accept your order. If your order is canceled after your credit card (or other payment account) has been charged, we will issue a credit to your credit card (or other applicable payment account) in the amount of the charge.")
				.append("\n\nPricing and Content Information\n\n",
						Typeface.BOLD)
				.append("While OnlineBazaar.pk strives to provide accurate pricing information, pricing or typographical errors may occur. OnlineBazaar.pk cannot confirm the price of an item until after you order. In the event that an item is listed at an incorrect price due to an error in pricing, OnlineBazaar.pk shall have the right, at OnlineBazaar.pk's sole discretion, to refuse or cancel any orders placed for that item. In the event that an item is mispriced, OnlineBazaar.pk may, at OnlineBazaar.pk's discretion, either contact you for instructions or cancel your order and notify you of such cancellation.\n")
				.append("We do our best to provide you with great values on the Site. OnlineBazaar.pk does not price match with any other online or offline retailer. We strive to maintain highly competitive prices and review them regularly in order to serve you with great values, every day.\n")
				.append("Customers employing mobile devices to browse the Site may encounter pricing or availability information that is either outdated or inaccurate. Accordingly, pricing and availability remain subject to confirmation at checkout for mobile users.\n")
				.append("Merchandise Content: OnlineBazaar.pk attempts to be accurate in its product descriptions. However, OnlineBazaar.pk does not warrant that product descriptions or other Content of this Site is accurate, complete, reliable, current, or error-free. If you find a product is not as described, your sole remedy is to return it in unused condition. \n")
				.append("Objectionable Content: You understand that by using this Site or any services provided on the Site, you may encounter Content that may be deemed by some to be offensive, indecent, or objectionable, which Content may or may not be identified as such. You agree to use the Site and any service at your sole risk and that OnlineBazaar.pk and its affiliates shall have no liability to you for Content that may be deemed offensive, indecent, or objectionable. \n")
				.append("\n\nQuantity Limits and Dealer Sales\n\n",
						Typeface.BOLD)
				.append("At OnlineBazaar.pk, we want you to be delighted every time you shop with us. You can always return items if they are defective or sent incorrect. Please know that you must provide us a written record of the reason for return or exchange within 24 hours of receiving the item. Custom, Oversize, or hazardous items cannot be returned. Items that have been used will not be accepted as returns or exchanges. Items which have any stains, emit, body odours or perfume scents, have any kind of marks, damages or water stains will not be accepted for returns or exchanges.\n")
				.append("There shall be a 10% handling charge of total price on all orders accepted for a refund.\n")
				.append("There is no refund for shipping and handling charges.")
				.append("\n\nCustoms/Duties/Taxes\n\n", Typeface.BOLD)
				.append("When ordering goods from OnlineBazaar.pk for delivery overseas you may be subject to pay import duties and taxes, which are levied once the package reaches the specified destination. Any additional charges for customs clearance must be paid by you; we have no control over these charges and cannot predict what they may be. Customs policies vary widely from country to country, so you should contact your local customs office for further information. ")
				.append("Additionally, please note that when ordering from OnlineBazaar.pk, you are considered the importer of record and must comply with all laws and regulations of the country in which you are receiving the goods. Your privacy is important to us and we know that you care about how information about your order is used and shared. We would like our international customers to be aware that cross-border deliveries are subject to opening and inspection by customs authorities.")
				.append("\n\nUser Reviews, Feedback, Submissions\n\n",
						Typeface.BOLD)
				.append("For all reviews, comments, feedback, postcards, suggestions, ideas, and other submissions disclosed, submitted or offered to OnlineBazaar.pk on or through this Site, by e-mail or telephone, or otherwise disclosed, submitted or offered in connection with your use of this Site (collectively, the \"Comments\") you grant OnlineBazaar.pk a royalty-free, irrevocable, transferable right and license to use the Comments however OnlineBazaar.pk desires, including without limitation, to copy, modify, delete in its entirety, adapt, publish, translate, create derivative works from and/or sell and/or distribute such Comments and/or incorporate such Comments into any form, medium or technology throughout the world. \n")
				.append("OnlineBazaar.pk will be entitled to use, reproduce, disclose, modify, adapt, create derivative works from, publish, display and distribute any Comments you submit for any purpose whatsoever, without restriction and without compensating you in any way. OnlineBazaar.pk is and shall be under no obligation (1) to maintain any Comments in confidence; (2) to pay to user any compensation for any Comments; or (3) to respond to any user Comments. ")
				.append(" You agree that any Comments submitted by you to the Site will not violate the terms in this Terms of Use or any right of any third party, including without limitation, copyright, trademark, privacy or other personal or proprietary right(s), and will not cause injury to any person or entity. You further agree that no Comments submitted by you to the Site will be or contain libelous or otherwise unlawful, threatening, abusive or obscene material, or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any form of \"spam\".")
				.append("OnlineBazaar.pk does not regularly review posted Comments, but does reserve the right (but not the obligation) to monitor and edit or remove any Comments submitted to the Site. You grant OnlineBazaar.pk the right to use the name that you submit in connection with any Comments. You agree not to use a false email address, impersonate any person or entity, or otherwise mislead as to the origin of any Comments you submit. ")
				.append("You are and shall remain solely responsible for the content of any Comments you make and you agree to indemnify OnlineBazaar.pk and its affiliates for all claims resulting from any Comments you submit. OnlineBazaar.pk and its affiliates take no responsibility and assume no liability for any Comments submitted by you or any third party. \n")
				.append("\n\nColors\n\n", Typeface.BOLD)
				.append("We have made significant efforts to accurately display the colors of our products that appear on the OnlineBazaar.pk. However, as the actual colors you see will depend on your monitor, we cannot guarantee that your monitor's display of any color will be accurate. \n")
				.append("\n\nIndemnification\n\n", Typeface.BOLD)
				.append("You agree to defend, indemnify and hold harmless OnlineBazaar.pk and its affiliates from and against any and all claims, damages, costs and expenses, including attorneys' fees, arising from or related to your use of the Site or any breach by you of these Terms of Use. \n")
				.append("\n\nTermination\n\n", Typeface.BOLD)
				.append("These Terms of Use are effective unless and until terminated by either you or OnlineBazaar.pk. You may terminate these Terms of Use at any time, provided that you discontinue any further use of this Site. OnlineBazaar.pk also may terminate these Terms of Use at any time and may do so immediately without notice, and accordingly deny you access to the Site, if in OnlineBazaar.pk's sole discretion you fail to comply with any term or provision of these Terms of Use.")
				.append("Upon any termination of these Terms of Use by either you or OnlineBazaar.pk, you must promptly destroy all materials downloaded or otherwise obtained from this Site, as well as all copies of such materials, whether made under the Terms of Use or otherwise. ")
				.append("The following sections shall survive any termination of these Terms of Use: \"Comments,\" \"Site Security,\" \"Pricing and Content Information,\" \"Quantity Limits and Dealer Sales,\" \"Customs/Duties/Taxes,\" \"Copyrights and Trademarks,\" \" User Reviews, Feedback and Submissions,\" \"Indemnification,\" \"Termination,\" \"Disclaimer\" \"Limitation of Liability,\" \"Privacy\" and \"General.\" ")
				.append("\n\nDisclaimer\n\n", Typeface.BOLD)
				.append("THIS SITE IS PROVIDED BY ONLINEBAZAAR.PK ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. ONLINEBAZAAR.PK MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE SITE OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS INCLUDED ON THIS SITE. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, ONLINEBAZAAR.PK DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. ")
				.append(" WITHOUT LIMITING THE FOREGOING, ONLINEBAZAAR.PK DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, FOR ANY MERCHANDISE OFFERED ON THIS SITE. YOU ACKNOWLEDGE, BY YOUR USE OF THE ONLINEBAZAAR.PK WEB SITE, THAT YOUR USE OF THE SITE IS AT YOUR SOLE RISK. THIS DISCLAIMER DOES NOT APPLY TO ANY PRODUCT WARRANTY OFFERED BY THE MANUFACTURER OF THE ITEM. THIS DISCLAIMER CONSTITUTES AN ESSENTIAL PART OF THESE TERMS OF USE. SOME PROVINCES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE FOREGOING LIMITATIONS MAY NOT APPLY TO YOU. \n")
				.append("MERCHANDISE CONTENT DISCLAIMER: PRODUCT INFORMATION ACCESSED THROUGH THIS WEBSITE IS OBTAINED FROM CLAIMS MADE BY THE PRODUCT'S MANUFACTURER. PLEASE NOTE THAT, ON OCCASION MANUFACTURERS MAY ALTER THEIR LABELS SO ACTUAL PRODUCT PACKAGING AND MATERIALS MAY CONTAIN DIFFERENT INFORMATION THAN THAT SHOWN ON OUR WEB SITE, THUS WE CANNOT GUARANTEE OR ENSURE THE ACCURACY, COMPLETENESS OR TIMELINESS OF ANY PRODUCT INFORMATION. ")
				.append("WE RECOMMEND THAT YOU DO NOT SOLELY RELY ON THE INFORMATION PRESENTED AND THAT YOU ALWAYS READ LABELS, WARNINGS, AND DIRECTIONS BEFORE USING OR CONSUMING A PRODUCT. FOR ADDITIONAL INFORMATION ABOUT A PRODUCT, PLEASE CONTACT THE MANUFACTURER. ONLINEBAZAAR.PK ASSUMES NO LIABILITY FOR INACCURACIES OR MISSTATEMENTS ABOUT PRODUCTS. CUSTOMER REVIEWS ARE PROVIDED FOR INFORMATIONAL PURPOSES ONLY. CUSTOMER REVIEWS REFLECT THE INDIVIDUAL REVIEWER'S RESULTS AND EXPERIENCES ONLY AND ARE NOT VERIFIED OR ENDORSED BY ONLINEBAZAAR.PK. ")
				.append("\n\nLimitation of Liability\n\n", Typeface.BOLD)
				.append("UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL OR EQUITABLE THEORY, WHETHER IN TORT, CONTRACT, STRICT LIABILITY OR OTHERWISE, SHALL ONLINEBAZAAR.PK OR ANY OF ITS AFFILIATES, EMPLOYEES, DIRECTORS, OFFICERS, AGENTS, VENDORS OR SUPPLIERS BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL LOSSES OR DAMAGES OF ANY NATURE ARISING OUT OF OR IN CONNECTION WITH THE USE OF OR INABILITY TO USE THE ONLINEBAZAAR.PK WEB SITE, ")
				.append("INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, LOSS OF DATA, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, EVEN IF AN AUTHORIZED REPRESENTATIVE OF ONLINEBAZAAR.PK HAS BEEN ADVISED OF OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL ONLINEBAZAAR.PK BE LIABLE FOR ANY DAMAGES IN EXCESS OF THE FEES PAID BY YOU IN CONNECTION WITH YOUR USE OF THE SITE DURING THE SIX MONTH PERIOD PRECEDING THE DATE ON WHICH THE CLAIM AROSE. ")
				.append("\n\nPrivacy\n\n", Typeface.BOLD)
				.append("You acknowledge that any personal information that you provide through this Site will be used by OnlineBazaar.pk in accordance with OnlineBazaar.pk's privacy policy. ")
				.append("\n\nGuest Checkout\n\n", Typeface.BOLD)
				.append("Guest Checkout is a feature on OnlineBazaar.pk that allows you to make purchases from our site without creating or using an account. While using Guest Checkout, you will be required to enter the following information: First and last name, year of birth, billing and shipping addresses, telephone number, credit card information and an email address where we can send order and shipping notifications. This information will not be saved on our site and you will have to re-enter it every time you use Guest Checkout.")
				.append("\n\nONLINEBAZAAR.PK CLICK-TO-CHAT TERMS AND CONDITIONS \n\n")
				.append("These terms and conditions (the \"Terms\") govern your conduct associated with the OnlineBazaar.pk Click-to-Chat Services (the \"Click-to-Chat Service\"). The information you provide will be handled according to OnlineBazaar.pk 's privacy policy. \n")
				.append("By using the Click-to-Chat Service, you represent and warrant that:\n\n")
				.append("\t\t-you are at least 13 years old;\n")
				.append("\t\t-information you supply does not violate these Terms and will not cause injury to any person or entity; and\n")
				.append("\t\t-you will use the information provided by a Click-to-Chat representative for your own personal use only.\n\n")
				.append("You further agree that:\n\n")
				.append("\t\t-you will not provide personal information about yourself or others as you use the Click-to-Chat Service, including, but not limited to, your full name, email, telephone number, CNIC or credit card information;\n\t\t-you will not take any actions that may undermine, disrupt or manipulate the integrity of the Click-to-Chat Service, or interfere with or disrupt the servers or networks connected to the Click-to-Chat Service;\n\t\t-you will not transmit through the Click-to-Chat Service any unlawful, harassing, libelous, privacy invading, abusive, threatening, defamatory, vulgar, obscene, racist or otherwise objectionable material of any kind;\n\t\t-you will not impersonate any person or entity, or make any false statement regarding your employment, agency or affiliation with any person or entity; and\n\t\t-you will not stalk, threaten or harass Click-to-Chat Service representatives or infringe upon or attempt to infringe upon their privacy.")
				.append("Your live chat with a Click-to-Chat representative is not public on the OnlineBazaar.pk website and is only seen between you and OnlineBazaar.pk. You will not have the ability to edit or delete any information you have submitted. OnlineBazaar.pk reserves the right to remove or to refuse to post any information for any reason. You acknowledge that you, not OnlineBazaar.pk, are responsible for the information you submit. \n")
				.append("Information a Click-to-Chat representative provides to you may be protected by copyright law, and you may only use such information for your own personal use. For any information that you submit, you grant OnlineBazaar.pk a perpetual, irrevocable, royalty-free, transferable right and license to use, copy, modify, delete in its entirety, adapt, publish, translate, create derivative works from and/or sell and/or distribute such information and/or incorporate such information into any form, medium or technology, including in connection with marketing and promotional purposes, throughout the world without compensation to you. ")
				.append("YOU EXPRESSLY UNDERSTAND AND AGREE THAT THE CLICK-TO-CHAT SERVICE IS PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. ONLINEBAZAAR.PK EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED. NO ADVICE OR INFORMATION OBTAINED BY YOU FROM YOUR USE OF THE CLICK-TO-CHAT SERVICE SHALL CREATE ANY WARRANTY. YOU UNDERSTAND AND AGREE THAT ONLINEBAZAAR.PK MAKES NO WARRANTY THAT THE QUALITY OF PRODUCTS PURCHASED BY YOU AT ONLINEBAZAAR.PK RELATED TO YOUR USE OF THE CLICK-TO-CHAT SERVICE WILL MEET YOUR EXPECTATIONS. \n")
				.append("You agree to indemnify and hold OnlineBazaar.pk (and its officers, directors, agents, subsidiaries, joint ventures, employees and third-party service providers), harmless from all claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown including reasonable attorneys' fees, arising out of a breach of your representations, warranties, and obligations set forth above, or your violation of any law or the rights of a third party.")
				.append("\n\nGeneral\n\n", Typeface.BOLD)
				.append("These Terms of Use represent the complete agreement between the parties and supersede all prior agreements and representations between them. Headings used in these Terms of Use are for reference purposes only and in no way define or limit the scope of the section. If any provision of these Terms of Use is held to be unenforceable for any reason, such provision shall be reformed only to the extent necessary to make it enforceable and the other terms of these Terms of Use shall remain in full force and effect. The failure of OnlineBazaar.pk to act with respect to a breach of these Terms of Use by you or others does not constitute a waiver and shall not limit OnlineBazaar.pk's rights with respect to such breach or any subsequent breaches. These Terms of Use shall be governed by and construed under British Common Law without regard to conflicts of law provisions.")
				.append("\n\nFor questions and concerns please call us at 0322-9229227, or email us at Care@onlinebazaar.pk",
						Typeface.BOLD);
		tvTermsAndCondition.setText(builder.toSpannableString());
	}

}
